- name: Configure MySQL Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL 8 Version
  ansible.builtin.shell: dnf module disable mysql -y

- name: Install MySQL Server Server and Python3 Dependency packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: installed