global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:
  - "record-rules.yml"
  - "alert-rules.yml"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'ec2-nodes'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: "tag:Monitor"
            values: [ "yes" ]
    relabel_configs:
      - source_labels: [ __meta_ec2_tag_Name ]
        target_label: Name
      - source_labels: [ __meta_ec2_tag_ENV ]
        target_label: ENV
      - source_labels: [ __meta_ec2_tag_COMPONENT ]
        target_label: COMPONENT



